[project]
name = "phub"
version = "4.7.6"
description = "An API for Pornhub"
authors = [
  {name = 'Egsagon', email = "egsagon.git@gmail.com"},
  {name = "EchterAlsFake", email = "EchterAlsFake@proton.me"}
]
license = {file = "LICENSE"}
readme = {file = "pypi.md", content-type = "text/markdown"}
keywords = ["pornhub", "phub", "porn", "api", "web scrapper", "api wrapper"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]
dependencies = ["httpx[brotli,socks]", "ffmpeg-progress-yield"]
requires-python = ">=3.9"


[project.scripts]
phub = "phub.__main__:main"

[project.urls]
Documentation = "https://phub.readthedocs.io"
Repository = "https://github.com/EchterAlsFake/PHUB"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
