[project]
name = "phub"
version = "4.0b"
description = "An API for Pornhub"
authors = [{name = "Egsagon", email = "egsagon.git@gmail.com"}]
license = {file = "LICENSE"}
readme = {file = "pypi.md", content-type = "text/markdown"}
keywords = ["pornhub", "api", "web scrapper", "api wrapper"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]
dependencies = [
    "requests",
    "tqdm"
]
requires-python = ">=3.11"

[project.optional-dependencies]
cli = ["click"]

[project.urls]
Documentation = "https://phub.readthedocs.io"
Repository = "https://github.com/Egsagon/PHUB"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]